scope:
  forarbeidsplassen: api://dev-gcp.teampam.pam-ad-api/.default
  kandidat-api: api://dev-fss.toi.rekrutteringsbistand-kandidat-api/.default

external:
  pam-ad-api.url: https://pam-ad-api.dev.intern.nav.no/adapi
  kandidatliste-api.url: https://rekrutteringsbistand-kandidat-api.nais.preprod.local/rekrutteringsbistand-kandidat-api/rest/veileder/stilling

spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_HOST}:${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_PORT}/${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_DATABASE}
    username: ${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_USERNAME}
    password: ${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_PASSWORD}
    driver: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5