scope:
  forarbeidsplassen: api://dev-gcp.teampam.pam-ad-api/.default
  kandidat-api: api://dev-fss.toi.rekrutteringsbistand-kandidat-api/.default

external:
  pam-ad-api.url: https://pam-ad-api.dev.intern.nav.no/adapi
  kandidatliste-api.url: https://rekrutteringsbistand-kandidat-api.dev-fss-pub.nais.io/rekrutteringsbistand-kandidat-api/rest/veileder/stilling

spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_STILLING_HOST}:${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_STILLING_PORT}/${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_STILLING_DATABASE}
    username: ${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_STILLING_USERNAME}
    password: ${NAIS_DATABASE_REKRUTTERINGSBISTAND_STILLING_API_REKRUTTERINGSBISTAND_STILLING_PASSWORD}
    driver: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, mappings